version: "4.0"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nba_db
    ports:
        - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  clickhouse
  dw:
    image: yandex/clickhouse-server
    container_name: clickhouse_dw
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
        - clickhouse_data:/var/lib/clickhouse

# apache airflow
# TODO: add apache airflow service


volumes:
  db_data:
    name: db_data
  clickhouse_data:
    name: clickhouse_data


